name: Check SARIF
description: Checks a SARIF file to see if certain queries were run and others were not run.
inputs:
  sarif-file:
    required: true
    description: The SARIF file to check

  queries-run:
    required: true
    description: |
      Comma separated list of query ids that should be included in this SARIF file.

  queries-not-run:
    required: true
    description: |
      Comma separated list of query ids that should NOT be included in this SARIF file.

runs:
  using: "composite"
  steps:
    - name: Run `check-sarif.ts`
      shell: bash
      env:
        SARIF_FILE: ${{ inputs.sarif-file }}
        QUERIES_RUN: ${{ inputs.queries-run }}
        QUERIES_NOT_RUN: ${{ inputs.queries-not-run }}
      run: |
        if [[ -d pr-checks ]]; then
          npx tsx ./pr-checks/check-sarif.ts \
            --sarif-file "$SARIF_FILE" \
            --queries-run "$QUERIES_RUN" \
            --queries-not-run "$QUERIES_NOT_RUN"
        else
          npx tsx ../action/pr-checks/check-sarif.ts \
            --sarif-file "$SARIF_FILE" \
            --queries-run "$QUERIES_RUN" \
            --queries-not-run "$QUERIES_NOT_RUN"
        fi
