name: "Proxy test"
description: "Tests using a proxy specified by the https_proxy environment variable"
versions: ["linked", "nightly-latest"]
container:
  image: ubuntu:22.04
services:
  squid-proxy:
    image: ubuntu/squid:latest
    ports:
      - 3128:3128
env:
  https_proxy: http://squid-proxy:3128
  CODEQL_ACTION_TOLERATE_MISSING_GIT_VERSION: true
steps:
  - uses: ./../action/init
    with:
      languages: javascript
      tools: ${{ steps.prepare-test.outputs.tools-url }}
  - uses: ./../action/analyze
