name: "Resolve environment"
description: "Tests that the resolve-environment action works for Go and JavaScript/TypeScript"
versions: ["stable-v2.13.5", "default", "linked", "nightly-latest"]
steps:
  - uses: ./../action/init
    with:
      languages: ${{ matrix.version == 'stable-v2.13.5' && 'go' || 'go,javascript-typescript' }}
      tools: ${{ steps.prepare-test.outputs.tools-url }}

  - name: Resolve environment for Go
    uses: ./../action/resolve-environment
    id: resolve-environment-go
    with:
      language: go

  - name: Fail if Go configuration missing
    if: (!fromJSON(steps.resolve-environment-go.outputs.environment).configuration.go)
    run: exit 1

  - name: Resolve environment for JavaScript/TypeScript
    if: matrix.version != 'stable-v2.13.5'
    uses: ./../action/resolve-environment
    id: resolve-environment-js
    with:
      language: javascript-typescript

  - name: Fail if JavaScript/TypeScript configuration present
    if: matrix.version != 'stable-v2.13.5' && fromJSON(steps.resolve-environment-js.outputs.environment).configuration.javascript
    run: exit 1
