name: "Proxy test"
description: "Tests using a proxy specified by the https_proxy environment variable"
versions: ["linked", "nightly-latest"]
operatingSystems: ["ubuntu"]
container:
  image: ubuntu:22.04
container-init-steps:
  # These steps are required to initialise the `gh` cli in a container that doesn't
  # come pre-installed with it. The reason for that is that this is later
  # needed by the `prepare-test` workflow to find the latest release of CodeQL. 
  name: Set up GitHub CLI
  run: |
    apt update
    apt install -y curl libreadline8 gnupg2 software-properties-common zstd
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    apt-key add /usr/share/keyrings/githubcli-archive-keyring.gpg
    apt-add-repository https://cli.github.com/packages
    apt install -y gh
  env: {}
services:
  squid-proxy:
    image: ubuntu/squid:latest
    ports:
      - 3128:3128
env:
  https_proxy: http://squid-proxy:3128
steps:
  - uses: ./../action/init
    with:
      languages: javascript
      tools: ${{ steps.prepare-test.outputs.tools-url }}
  - uses: ./../action/analyze
