name: "Proxy test"
description: "Tests using a proxy specified by the https_proxy environment variable"
versions: ["latest"]
operatingSystems: ["ubuntu"]
container:
  image: ubuntu:18.04
  options: --dns 127.0.0.1
services:
  agent-proxy:
    image: datadog/agent:latest
    ports:
      - 3128:3128
env:
  https_proxy: http://agent-proxy:3128
steps:
  - uses: ./../action/init
    with:
      languages: javascript
      tools: ${{ steps.prepare-test.outputs.tools-url }}
    env:
      TEST_MODE: true
  - uses: ./../action/analyze
    env:
      TEST_MODE: true
