repos:
  - repo: local
    hooks:
      - id: lint-ts
        name: Lint typescript code
        files: \.ts$
        language: system
        entry: npm run lint -- --fix
      - id: compile-ts
        name: Compile typescript
        files: \.[tj]s$
        language: system
        entry: npm run build
        pass_filenames: false
      - id: pr-checks-sync
        name: Synchronize PR check workflows
        files: ^.github/workflows/__.*\.yml$|^pr-checks
        language: system
        entry: pr-checks/sync.sh
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.8.0
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
