name: "Set up Swift on Linux"
description: Sets up an appropriate Swift version on Linux.
inputs:
  codeql-path:
    description: Path to the CodeQL CLI executable.
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Swift version
      id: get_swift_version
      if: runner.os == 'Linux'
      shell: bash
      env:
        CODEQL_PATH: ${{ inputs.codeql-path }}
      run: |
        SWIFT_EXTRACTOR_DIR="$("$CODEQL_PATH" resolve languages --format json | jq -r '.swift[0]')"
        if [ $SWIFT_EXTRACTOR_DIR = "null" ]; then
          VERSION="null"
        else
          VERSION="$("$SWIFT_EXTRACTOR_DIR/tools/linux64/extractor" --version | awk '/version/ { print $3 }')"
          # Specify 5.x.0, otherwise setup Action will default to latest minor version.
          if [ $VERSION = "5.7" ]; then
            VERSION="5.7.0"
          elif [ $VERSION = "5.8" ]; then
            VERSION="5.8.0"
          elif [ $VERSION = "5.9" ]; then
            VERSION="5.9.0"
          # setup-swift does not yet support v5.9.1 Remove this when it does.
          elif [ $VERSION = "5.9.1" ]; then
            VERSION="5.9.0"
          fi
        fi
        echo "version=$VERSION" | tee -a $GITHUB_OUTPUT

    - uses: redsun82/setup-swift@362f49f31da2f5f4f851657046bdd1290d03edc8 # Please update the corresponding SHA in the CLI's CodeQL Action Integration Test.
      if: runner.os == 'Linux' && steps.get_swift_version.outputs.version != 'null'
      with:
        swift-version: "${{ steps.get_swift_version.outputs.version }}"
