name: "Set up Swift"
description: Sets up an appropriate Swift version if supported on this platform.
inputs:
  codeql-path:
    description: Path to the CodeQL CLI executable.
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Swift version
      id: get_swift_version
      if: runner.os != 'Windows'
      shell: bash
      env: 
        CODEQL_PATH: ${{ inputs.codeql-path }}
      run: |
        if [[ $RUNNER_OS = "macOS" ]]; then
          PLATFORM="osx64"
        else # We do not run this step on Windows.
          PLATFORM="linux64"
        fi 
        SWIFT_EXTRACTOR_DIR="$("$CODEQL_PATH" resolve languages --format json | jq -r '.swift[0]')"
        if [ $SWIFT_EXTRACTOR_DIR = "null" ]; then
          VERSION="null"
        else
          VERSION="$("$SWIFT_EXTRACTOR_DIR/tools/$PLATFORM/extractor" --version | awk '/version/ { print $3 }')"
          # Specify 5.x.0, otherwise setup Action will default to latest minor version. 
          if [ $VERSION = "5.7" ]; then
            VERSION="5.7.0"
          elif [ $VERSION = "5.8" ]; then
            VERSION="5.8.0"
          # setup-swift does not yet support v5.8.1 Remove this when it does.
          elif [ $VERSION = "5.8.1" ]; then
            VERSION="5.8.0"
          fi 
        fi
        echo "version=$VERSION" | tee -a $GITHUB_OUTPUT
    - name: Log disk info on Linux prior to setup-swift
      shell: bash
      run: |-
          if ! hash sudo &> /dev/null; then apt-get update -q=2 && apt-get install sudo -y -q=2; fi;
          sudo df -h
      if: runner.os == 'Linux'
    - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf # Please update the corresponding SHA in the CLI's CodeQL Action Integration Test.
      if: runner.os != 'Windows' && steps.get_swift_version.outputs.version != 'null'
      with:
        swift-version: "${{ steps.get_swift_version.outputs.version }}"
    - name: Log disk info on Linux after setup-swift
      shell: bash
      run: |-
          if ! hash sudo &> /dev/null; then apt-get update -q=2 && apt-get install sudo -y -q=2; fi;
          sudo df -h
      if: runner.os == 'Linux'