name: 'CodeQL: Finish'
description: 'Finalize CodeQL database'
author: 'GitHub'
inputs:
  check_name:
    description: The name of the check run to add text to.
    required: false
  output:
    description: The path of the directory in which to save the SARIF results
    required: false
    default: '../results'
  upload:
    description: Upload the SARIF file
    required: false
    default: "true"
  ram:
    description: Override the amount of memory in MB to be used by CodeQL. By default, almost all the memory of the machine is used.
    required: false
  add-snippets:
    description: Specify whether or not to add code snippets to the output sarif file.
    required: false
    default: "false"
  threads:
    description: The number of threads to be used by CodeQL.
    required: false
  checkout_path:
    description: "The path at which the analyzed repository was checked out. Used to relativize any absolute paths in the uploaded SARIF file."
    required: false
    default: ${{ github.workspace }}
  token:
    default: ${{ github.token }}
  matrix:
    default: ${{ toJson(matrix) }}
runs:
  using: 'node12'
  main: '../lib/analyze-action.js'
