/* This file was automatically generated by `npm run generate:schemas`. Do not edit by hand. */

/**
 * Format of the config file supplied by the user for CodeQL analysis
 */
export interface UserConfig {
  /**
   * Name of the configuration
   */
  name?: string;
  /**
   * Whether to disable default queries
   */
  "disable-default-queries"?: boolean;
  /**
   * List of additional queries to run
   */
  queries?: QuerySpec[];
  /**
   * Paths to ignore during analysis
   */
  "paths-ignore"?: string[];
  /**
   * Paths to include in analysis
   */
  paths?: string[];
  /**
   * Query packs to include. Can be a simple array for single-language analysis or an object with language-specific arrays for multi-language analysis
   */
  packs?:
    | string[]
    | {
        [k: string]: string[];
      };
  /**
   * Set of query filters to include and exclude extra queries based on CodeQL query suite include and exclude properties
   */
  "query-filters"?: unknown[];
  [k: string]: unknown;
}
/**
 * Detailed query specification object
 */
export interface QuerySpec {
  /**
   * Optional name for the query
   */
  name?: string;
  /**
   * The query or query suite to use
   */
  uses: string;
}
