#!/usr/bin/env npx tsx

/**
 * Checks the code scanning configuration file generated by the
 * action to ensure it contains the expected contents
 */

import * as assert from "node:assert";
import * as fs from "node:fs";
import { parseArgs } from "node:util";

import * as core from "@actions/core";
import * as yaml from "yaml";

import type { UserConfig } from "../src/config/db-config";

import { getErrorMessage } from "./util";

function sortConfigArrays(config: UserConfig) {
  for (const key of Object.keys(config)) {
    const value = config[key];
    if (key === "queries" && Array.isArray(value)) {
      config[key] = value.sort();
    }
  }
  return config;
}

function loadActualConfig(configPath: string) {
  if (!fs.existsSync(configPath)) {
    throw new Error("No configuration file found");
  } else {
    const rawActualConfig = fs.readFileSync(configPath, "utf8");
    core.startGroup("Actual generated user config");
    core.info(rawActualConfig);
    core.endGroup();

    return yaml.parse(rawActualConfig) as UserConfig;
  }
}

export function checkConfiguration(
  actualConfig: UserConfig,
  expectedContents: string,
) {
  const rawExpectedConfig = expectedContents.trim();
  if (!rawExpectedConfig) {
    throw new Error("No expected configuration provided");
  }

  const expectedConfig = JSON.parse(rawExpectedConfig) as UserConfig;

  core.startGroup("Expected generated user config");
  core.info(yaml.stringify(expectedConfig));
  core.endGroup();

  assert.deepStrictEqual(
    sortConfigArrays(actualConfig),
    sortConfigArrays(expectedConfig),
    "Expected configuration does not match actual configuration",
  );
}

function main() {
  const { values } = parseArgs({
    options: {
      // The path of the configuration file to check.
      file: {
        type: "string",
      },
      // The expected contents of the file.
      "expected-contents": {
        type: "string",
      },
    },
    strict: true,
  });

  if (values.file === undefined) {
    throw new Error("The '--file' input is required.");
  }
  if (values["expected-contents"] === undefined) {
    throw new Error("The '--expected-contents' input is required.");
  }

  const actualConfig = loadActualConfig(values.file);

  try {
    checkConfiguration(actualConfig, values["expected-contents"]);
  } catch (err) {
    core.error(getErrorMessage(err));
    return -1;
  }

  return 0;
}

if (require.main === module) {
  process.exit(main());
}
