# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pr-checks/sync.sh
# to regenerate this file.

name: 'PR Check - Bundle: Caching checks'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs: {}
  workflow_call:
    inputs: {}
defaults:
  run:
    shell: bash
concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  bundle-toolcache:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            version: linked
          - os: ubuntu-latest
            version: linked
          - os: windows-latest
            version: linked
    name: 'Bundle: Caching checks'
    if: github.triggering_actor != 'dependabot[bot]'
    permissions:
      contents: read
      security-events: read
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Remove CodeQL from toolcache
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const codeqlPath = path.join(process.env['RUNNER_TOOL_CACHE'], 'CodeQL');
            fs.rmdirSync(codeqlPath, { recursive: true });
      - name: Install @actions/tool-cache
        run: npm install @actions/tool-cache
      - name: Check toolcache does not contain CodeQL
        uses: actions/github-script@v8
        with:
          script: |
            const toolcache = require('@actions/tool-cache');
            const allCodeqlVersions = toolcache.findAllVersions('CodeQL');
            if (allCodeqlVersions.length !== 0) {
              throw new Error(`CodeQL should not be found in the toolcache, but found ${allCodeqlVersions}`);
            }
            console.log('No versions of CodeQL found in the toolcache');
      - id: init
        uses: ./../action/init
        with:
          languages: javascript
          tools: ${{ steps.prepare-test.outputs.tools-url }}
      - uses: ./../action/analyze
        with:
          output: ${{ runner.temp }}/results
          upload-database: false
      - name: Check CodeQL is installed within the toolcache
        uses: actions/github-script@v8
        with:
          script: |
            const toolcache = require('@actions/tool-cache');
            const allCodeqlVersions = toolcache.findAllVersions('CodeQL');
            console.log(`Found CodeQL versions: ${allCodeqlVersions}`);
            if (allCodeqlVersions.length === 0) {
              throw new Error('CodeQL not found in toolcache');
            }
            if (allCodeqlVersions.length > 1) {
              throw new Error('Multiple CodeQL versions found in toolcache');
            }
    env:
      CODEQL_ACTION_TEST_MODE: true
