# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pr-checks/sync.sh
# to regenerate this file.

name: 'PR Check - Bundle: Zstandard checks'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  merge_group:
    types:
      - checks_requested
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs: {}
  workflow_call:
    inputs: {}
defaults:
  run:
    shell: bash
concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' || false }}
  group: bundle-zstd-${{github.ref}}
jobs:
  should-run-bundle-zstd:
    name: Decide whether to run this check
    timeout-minutes: 10
    runs-on: ubuntu-slim
    if: github.triggering_actor != 'dependabot[bot]'
    outputs:
      run-check: ${{ steps.changed-files-check.outputs.run-check || steps.event-type-check.outputs.run-check }}
    steps:
      - name: Run check if this is not a PR
        id: event-type-check
        if: github.event_name != 'pull_request'
        run: echo "run-check=true" >> "$GITHUB_OUTPUT"
      - name: Check out repository
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v6
      - name: Determine changed files
        id: changed-files
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/changed-files
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '["README.md"]'
      - name: Run check because of changed files
        id: changed-files-check
        if: github.event_name != 'pull_request' && steps.changed-files.outputs.files != '[]'
        run: echo "run-check=true" >> "$GITHUB_OUTPUT"
  bundle-zstd:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version: linked
          - os: macos-latest
            version: linked
          - os: windows-latest
            version: linked
    name: 'Bundle: Zstandard checks'
    needs:
      - should-run-bundle-zstd
    if: needs.should-run-bundle-zstd.outputs.run-check == 'true'
    permissions:
      contents: read
      security-events: read
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Remove CodeQL from toolcache
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const codeqlPath = path.join(process.env['RUNNER_TOOL_CACHE'], 'CodeQL');
            if (codeqlPath !== undefined) {
              fs.rmdirSync(codeqlPath, { recursive: true });
            }
      - id: init
        uses: ./../action/init
        with:
          languages: javascript
          tools: ${{ steps.prepare-test.outputs.tools-url }}
      - uses: ./../action/analyze
        with:
          output: ${{ runner.temp }}/results
          upload-database: false
      - name: Upload SARIF
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-zstd-bundle.sarif
          path: ${{ runner.temp }}/results/javascript.sarif
          retention-days: 7
      - name: Check diagnostic with expected tools URL appears in SARIF
        uses: actions/github-script@v8
        env:
          SARIF_PATH: ${{ runner.temp }}/results/javascript.sarif
        with:
          script: |
            const fs = require('fs');

            const sarif = JSON.parse(fs.readFileSync(process.env['SARIF_PATH'], 'utf8'));
            const run = sarif.runs[0];

            const toolExecutionNotifications = run.invocations[0].toolExecutionNotifications;
            const downloadTelemetryNotifications = toolExecutionNotifications.filter(n =>
              n.descriptor.id === 'codeql-action/bundle-download-telemetry'
            );
            if (downloadTelemetryNotifications.length !== 1) {
              core.setFailed(
                'Expected exactly one reporting descriptor in the ' +
                  `'runs[].invocations[].toolExecutionNotifications[]' SARIF property, but found ` +
                  `${downloadTelemetryNotifications.length}. All notification reporting descriptors: ` +
                  `${JSON.stringify(toolExecutionNotifications)}.`
              );
            }

            const toolsUrl = downloadTelemetryNotifications[0].properties.attributes.toolsUrl;
            console.log(`Found tools URL: ${toolsUrl}`);

            const expectedExtension = process.env['RUNNER_OS'] === 'Windows' ? '.tar.gz' : '.tar.zst';

            if (!toolsUrl.endsWith(expectedExtension)) {
              core.setFailed(
                `Expected the tools URL to be a ${expectedExtension} file, but found ${toolsUrl}.`
              );
            }
    env:
      CODEQL_ACTION_TEST_MODE: true
  skip-bundle-zstd:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            version: linked
          - os: ubuntu-latest
            version: linked
          - os: windows-latest
            version: linked
    name: 'Bundle: Zstandard checks'
    needs:
      - should-run-bundle-zstd
    if: needs.should-run-bundle-zstd.outputs.run-check != 'true'
    timeout-minutes: 5
    runs-on: ubuntu-slim
    steps:
      - name: Success
        run: exit 0
