# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pr-checks/sync.sh
# to regenerate this file.

name: PR Check - Build mode autobuild
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      java-version:
        type: string
        description: The version of Java to install
        required: false
        default: '17'
  workflow_call:
    inputs:
      java-version:
        type: string
        description: The version of Java to install
        required: false
        default: '17'
defaults:
  run:
    shell: bash
concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-mode-autobuild:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version: linked
          - os: windows-latest
            version: linked
          - os: ubuntu-latest
            version: nightly-latest
          - os: windows-latest
            version: nightly-latest
    name: Build mode autobuild
    if: github.triggering_actor != 'dependabot[bot]'
    permissions:
      contents: read
      security-events: read
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version || '17' }}
          distribution: temurin
      - name: Set up Java test repo configuration
        run: |
          mv * .github ../action/tests/multi-language-repo/
          mv ../action/tests/multi-language-repo/.github/workflows .github
          mv ../action/tests/java-repo/* .

      - uses: ./../action/init
        id: init
        with:
          build-mode: autobuild
          db-location: ${{ runner.temp }}/customDbLocation
          languages: java
          tools: ${{ steps.prepare-test.outputs.tools-url }}

      - name: Install yq
        if: runner.os == 'Windows'
        run: |
          choco install yq -y

      - name: Validate database build mode
        run: |
          metadata_path="$RUNNER_TEMP/customDbLocation/java/codeql-database.yml"
          build_mode=$(yq eval '.buildMode' "$metadata_path")
          if [[ "$build_mode" != "autobuild" ]]; then
            echo "Expected build mode to be 'autobuild' but was $build_mode"
            exit 1
          fi

      - name: Check that indirect tracing is disabled
        run: |
          if [[ ! -z "${CODEQL_RUNNER}" ]]; then
            echo "Expected indirect tracing to be disabled, but the" \
              "CODEQL_RUNNER environment variable is set."
            exit 1
          fi

      - uses: ./../action/analyze
    env:
      CODEQL_ACTION_TEST_MODE: true
