# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     (cd pr-checks; pip install ruamel.yaml@0.17.31 && python3 sync.py)
# to regenerate this file.

name: PR Check - Config input
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}
jobs:
  config-input:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version: linked
    name: Config input
    permissions:
      contents: read
      security-events: read
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Copy queries into workspace
        run: |
          cp -a ../action/queries .

      - uses: ./../action/init
        with:
          tools: ${{ steps.prepare-test.outputs.tools-url }}
          languages: javascript
          build-mode: none
          config: |
            disable-default-queries: true
            queries:
              - name: Run custom query
                uses: ./queries/default-setup-environment-variables.ql
            paths-ignore:
              - tests
              - lib

      - uses: ./../action/analyze
        with:
          output: ${{ runner.temp }}/results

      - name: Check SARIF
        uses: ./../action/.github/actions/check-sarif
        with:
          sarif-file: ${{ runner.temp }}/results/javascript.sarif
          queries-run: javascript/codeql-action/default-setup-env-vars
          queries-not-run: javascript/codeql-action/default-setup-context-properties
    env:
      CODEQL_ACTION_TEST_MODE: true
