name: 'Publish Immutable Action Version'

on:
  push:
    tags:
      # Match version tags, but not the major version tags.
      - 'v[0-9]+.**'

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Publish immutable release
        id: publish
        uses: actions/publish-immutable-action@4bc8754ffc40f27910afb20287dbbbb675a4e978 # v0.0.4
