name: Test that the workaround for python 3.12 on windows works

on:
  push:
    branches: [main, releases/v*]
  pull_request:
    # Run checks on reopened draft PRs to support triggering PR checks on draft PRs that were opened
    # by other workflows.
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    # Weekly on Monday.
    - cron: '0 0 * * 1'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-setup-python-scripts:
    if: github.triggering_actor != 'dependabot[bot]'
    env:
      CODEQL_ACTION_TEST_MODE: true
    timeout-minutes: 45
    permissions:
      contents: read
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - uses: actions/checkout@v5

    - name: Prepare test
      uses: ./.github/actions/prepare-test
      with:
        version: default

    - name: Initialize CodeQL
      uses: ./../action/init
      with:
        tools: linked
        languages: python

    - name: Analyze
      uses: ./../action/analyze
