name: Test that the workaround for python 3.12 on windows works

on:
  push:
    branches: [main, releases/v*]
  pull_request:
  merge_group:
    types: [checks_requested]
  schedule:
    # Weekly on Monday.
    - cron: '0 0 * * 1'
  workflow_dispatch:

concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' || false }}
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  test-setup-python-scripts:
    if: github.triggering_actor != 'dependabot[bot]'
    env:
      CODEQL_ACTION_TEST_MODE: true
    timeout-minutes: 45
    permissions:
      contents: read
      # We currently need `security-events: read` to access feature flags.
      security-events: read
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.12

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Prepare test
      uses: ./.github/actions/prepare-test
      with:
        version: default

    - name: Initialize CodeQL
      uses: ./../action/init
      with:
        tools: linked
        languages: python

    - name: Analyze
      uses: ./../action/analyze
